# Generated by Django 2.1.2 on 2018-10-26 00:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cuenta_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuentas', to=settings.AUTH_USER_MODEL),
        ),
    ]
