# Generated by Django 2.1.2 on 2018-11-01 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_cliente_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuenta',
            name='deposito',
        ),
    ]
