# Generated by Django 2.1.2 on 2018-11-19 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_cuenta_deposito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='saldo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='api.Perfil'),
        ),
    ]
