# Generated by Django 2.1.2 on 2018-11-19 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20181119_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='saldo',
            field=models.IntegerField(default=0),
        ),
    ]
