# Generated by Django 2.1.2 on 2018-11-20 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20181119_0117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='cuenta',
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='perfil',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Cuenta',
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
        migrations.DeleteModel(
            name='Transaccion',
        ),
    ]
